name: workflow1

on:
 
  push:
    
jobs:
 
  construir:
    
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Setup Node.js environment
        uses: actions/setup-node@v5.0.0
      
      - name: Imprimir multiples lineas
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo Hola Mundo
          echo Patricio Alvear
  
 
  deployar:
    
    runs-on: ubuntu-latest
    needs: construir
    steps:
    
      - name: Deploy
        run: npm -version   
     