name: workflow1

on:
 
  push:
    
jobs:
 
  construir:
    
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.35.5
        with:
          php-version: '8.3'


  instalar:
    
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v5.0.0
        with: 
          node-version: latest
      
         
 
     