name: Hola Mundo
on: [push]

jobs:
    hola:
        runs-on: ubuntu-latest

        services:
          mysql:
            image: mysql
            env:
              MYSQL_ROOT_PASSWORD: admin
            ports:
              - 3306:3306  
        steps: 
        - name: Imprimir variable
          run: echo "Valor variable ${{vars.BASEDEDATOS}}"      
   