name: workflow1

on:
 
  push:
    
jobs:
 
  construir:
    
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Listar
        run: ls -al
    
         
 
     