name: workflow1

on:
 
  push:
    
jobs:
 
  construir:
    
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Hola Mundo
        run: echo Hello, world!
      
      - name: Imprimir multiples lineas
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo Hola Mundo
          echo Patricio Alvear

  deployar:
    
    runs-on: ubuntu-latest
    needs: construir
    steps:
    
      - name: Deploy
        run: echo Estoy haciendo un deploy     
     